---
title: "tesseract"
author: "Drew Walker"
date: "6/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tesseract)
library(tidyverse)
library(lubridate)
library(magick)
```

```{r, loadimage}
eng <- tesseract("eng")
text <- tesseract::ocr("http://jeroen.github.io/images/testocr.png", engine = eng)
cat(text)
```

```{r, evaluation}
results <- tesseract::ocr_data("http://jeroen.github.io/images/testocr.png", engine = eng)
results
```

```{r, tesseractdownload-training}
# Only need to do download once:
tesseract_download("nld")

(dutch <- tesseract("nld"))
text <- ocr("https://jeroen.github.io/images/utrecht2.png", engine = dutch)
cat(text)
```

```{r, fakecensus}

```


```{r, magick-processing}

input <- image_read("fakecensus.png")

text <- input %>%
  image_resize("2000x") %>%
  image_convert(type = 'Grayscale') %>%
  image_trim(fuzz = 40) %>%
  image_write(format = 'png', density = '300x300') %>%
  tesseract::ocr() 

cat(text)

#need to add lines to this

library(stringr)
library(tm)

dat <- map(text, function(x) {
  tibble(text = unlist(str_split(x, pattern = " "))) %>%
    rowid_to_column(var = "line")
})

tibble <- dat[[1]] 

str(tibble_clean)

tibble_clean$textdata

tibble_clean <- tibble %>% 
  rename(textdata = text) 

corpus <- Corpus(VectorSource(tibble_clean$textdata))

corpus = tm_map(corpus, PlainTextDocument)



census_date <- corpus[[1]][[1]][6:7] 
census_date_clean <- census_date %>% 
  paste(collapse = " ")
census_date_as_date <- mdy(census_date_clean)

tibble_dated <- tibble_clean %>% 
  mutate(date = census_date_as_date)

filename <- paste("Census",census_date_as_date)
# remove punctuation
corpus = tm_map(corpus, removePunctuation)
corpus[[1]][1]

corptibble <- as_tibble(unlist(corpus$content))


corptibble2 <-  gsub("([a-z])([A-Z])", "\\1 \\2",corptibble)

corptibble3 <- as_tibble_col(corptibble2)


new <- 
corpus$content


#Need to grab date from first line 
#need to grab names from this and list them rowwise. 
#Then mutate date column piping in value from date extraction
```

```{r, census-evaluation}
results <- tesseract::ocr_data("fakecensus.png", engine = "eng")
results
```


```{r, frompdffiles}
pngfile <- pdftools::pdf_convert('https://jeroen.github.io/images/ocrscan.pdf', dpi = 600)
```

```{r, showpdftext}
text <- tesseract::ocr(pngfile)
cat(text)
```

```{r, practice}


pngfile <- pdftools::pdf_convert("Proctor2011_Article_OutcomesForImplementationResea.pdf", dpi = 600)

text <- tesseract::ocr(pngfile)
cat(text)

```

